### PR TITLE
Fix some package detections

### LINKED ISSUE #98: Failed to load/activate package bug should be filed on package not Atom?
I'm seeing a lot of these:

* https://github.com/atom/atom/issues/9416
* https://github.com/atom/atom/issues/9410
* https://github.com/atom/atom/issues/9396
* https://github.com/atom/atom/issues/9394
* https://github.com/atom/atom/issues/9364
* https://github.com/atom/atom/issues/9350
* ...

Most likely the issue is with the code in the package, not Atom, yes? Even though the stack trace doesn't mention the package ... perhaps for this specific message we should file it on the package first?

### PR DESCRIPTION
**Pull request by 50Wliu**
:warning: Sorta-kinda depends on atom/atom#9440, which has not been released yet :warning:

This fixes the following scenarios:
* A package fails to load and throws a "Failed to load the \<package\> package" error
* A package fails to activate and throws a "Failed to activate the \<package\> package" error
* A grammar fails to load and throws a "Failed to load a \<package\> package grammar" error
* A package that has been `apm link`ed on a Windows machine throws an error

All of those would previously fail to find the correct package to report the issue to and so they were all dumped to atom/atom.

Refs #66
Fixes #98

### CODE REVIEW

**Comment by 50Wliu** [comment]
Hmm.  The linked package test was passing locally, but that was on Windows.  I'll try to debug tomorrow on Linux unless someone figures out what I'm doing wrong before that ;).

File: lib/notification-issue.coffee [hunk 1]
```diff
@@ -174,12 +174,13 @@ class NotificationIssue
...
   getPackageName: ->
+    message = @notification.getMessage()
     options = @notification.getOptions()
-    return unless options.stack? or options.detail?
+    return unless message? or options.stack? or options.detail?
 
     packagePaths = @getPackagePathsByPackageName()
     for packageName, packagePath of packagePaths
-      if packagePath.indexOf('.atom/dev/packages') > -1 or packagePath.indexOf('.atom/packages') > -1
+      if packagePath.indexOf(path.join('.atom', 'dev', 'packages')) > -1 or packagePath.indexOf(path.join('.atom', 'packages')) > -1
```
Comment (benogle) [inline lib/notification-issue.coffee]: oh man. Cant believe this has been in there so long.

**Comment by izuzak** [comment]
👏 @50Wliu 

Going to cc @kevinsawicki for more 👀 since he worked on some improvement to this package and error detection, if I remember correctly.

File: lib/notification-issue.coffee [hunk 2]
```diff
@@ -190,6 +191,9 @@ class NotificationIssue
           return packName unless /^\.\./.test(relativePath)
       @getPackageNameFromFilePath(filePath)
 
+    packageName = /Failed to (load|activate) (the|a) (.*) package/.exec(message)?[3]
```
Comment (kevinsawicki) [inline lib/notification-issue.coffee]: I wonder if we should pass in the `packageName` as metadata to the notification instead of having to regex the message.

Comment (50Wliu) [inline lib/notification-issue.coffee]: Yeah, that would probably be better.  Any pointers on how to do that?

**Comment by 50Wliu** [comment]
Unfortunately I can't reproduce the failing spec, even on Ubuntu :disappointed:.

File: lib/notification-issue.coffee (hunk 2 above)
Comment (kevinsawicki) [inline lib/notification-issue.coffee]: Yeah, I wonder if putting it in this payload would be sufficient, https://github.com/atom/atom/blob/666bb344647d1f96df93c875e404e32bd6c1d419/src/package.coffee#L637

Comment (benogle) [inline lib/notification-issue.coffee]: And here: https://github.com/atom/atom/blob/666bb344647d1f96df93c875e404e32bd6c1d419/src/package-manager.coffee#L470 (and maybe in other places)

For reference, grim supports a packageName in the metadata: https://github.com/atom/grim/blob/82c45ef794ce93e4455c29365441c62bf94b90a8/spec/grim-spec.coffee#L108

File: lib/notification-issue.coffee (hunk 1 above)
Comment (50Wliu) [inline lib/notification-issue.coffee]: I think this still might be incorrect...@kevinsawicki if someone sets their `ATOM_HOME` to something like `/Users/user/ATOM`, then will this check fail?  If so, how would I fix that?  By reading `process.env.ATOM_HOME` and then regexing it to capture the last folder path?

**Comment by 50Wliu** [comment]
Wow ok so I *totally* forgot that package specs run on Mac and not Linux.  Can anyone repro the failing spec on Mac then?

**Comment by 50Wliu** [comment]
Also, should we switch to actually building and then loading a package (similar to how spec/package-manager-spec.coffee does it) instead of manually creating the notification ourselves?

File: lib/notification-issue.coffee [hunk 3]
```diff
@@ -190,6 +190,8 @@ class NotificationIssue
           return packName unless /^\.\./.test(relativePath)
       @getPackageNameFromFilePath(filePath)
 
+    return options.packageName if options.packageName?
```
Comment (benogle) [inline lib/notification-issue.coffee]: Seems like this could be returned at the top of this method? Like line 178?

File: lib/notification-issue.coffee (hunk 1 above)
Comment (benogle) [inline lib/notification-issue.coffee]: Gentle bump @kevinsawicki

Comment (kevinsawicki) [inline lib/notification-issue.coffee]: The goal of this line is to check if the package is bundled or not right?

There is `atom.packages.isBundledPackage` and `atom.packages.isBundledPackagePath` that might be useful to use instead.

Comment (50Wliu) [inline lib/notification-issue.coffee]: I think it's actually to check if a package is symlinked or not, and then to get its true path since that's where the error will have been thrown from.

Eg if I have notifications linked to `.atom\packages\notifications` from `C:\Users\user\Documents\Github\notifications` and notifications throws an error, then this piece of code will correctly match the two.

Comment (kevinsawicki) [inline lib/notification-issue.coffee]: Oh yeah, I'd say maybe just call `fs.realpath` in all cases then if we want to ensure the stack paths match the package paths.

**Comment by maxbrunsfeld** [comment]
:ship:

**Comment by 50Wliu** [comment]
> :ship: 

Whoops, missed that...

**Comment by as-cii** [comment]
Thanks, @50Wliu!
