### PR TITLE
Adding fix for bug with having new lines as part of title.

### LINKED ISSUE #156: Unable to detect existing issue.
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Steps to Reproduce

This is hard to repro, but we know this is happening because of: https://github.com/atom/atom/issues/11692

I was able to dig in and saw that there was an issue in the whitespace.  I changed the code to get a repro.  

steps to repro with code change...  

1. check out this repo, 
2. checkout branch `ungb-finding-issue-issue`
3. run `apm install && apm link` for this repo
4.  cause an error to occur on another package or something.  
5. open dev tools to see the issue with whitespace.

The data in here is hard coded 

**Expected behavior:** [What you expect to happen]
The error message should match for https://github.com/atom/atom/issues/11692 and all it's dup, but doesn't.

**Actual behavior:** [What actually happens]
ask you to create a new issue.  

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% of the time.

### Versions
Atom 1.17.0 stable.

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

I'll try to take a look but creating this issue for tracking.

### PR DESCRIPTION
**Pull request by ungb**
### Description of the Change
Error message with \n or new lines are being left out when it comes back from github api server.  

see https://api.github.com/search/issues?q=Uncaught%20Error%3A%20Cannot%20read%20property%20%27object%27%20of%20undefinedTypeError%3A%20Cannot%20read%20property%20%27objec...%20repo%3Aatom%2Fatom

the 

getIssueTitle() function doesn't escape newlines.

### Alternate Designs
Could just for escape newline in checking logic, but decided that having newline in title is a bit weird so opted to add it to getIssueTitle().

Seeing how existing issues already created with \n.  If we need to truncate the text, we would take into consider the \n as a character and add additional buffer.  

### Benefits
Titles in issues will look better going forward and people will stop the massive dup of issues that are created.

fixes #156 

### Possible Drawbacks

N/A

### Applicable Issues

#156 

/cc @as-cii @jasonrudolph @iolsen for feedback.

### CODE REVIEW

File: lib/notification-issue.coffee [hunk 1]
```diff
@@ -70,7 +70,7 @@ class NotificationIssue
 
     if title.length > TITLE_CHAR_LIMIT
       title = title.substring(0, TITLE_CHAR_LIMIT - 3) + '...'
-    title
+    title.replace(/\r?\n|\r/g,"");
```
Comment (jasonrudolph) [inline lib/notification-issue.coffee]: @ungb: When you have a moment, can you take a look at the [build failure related to this change](https://travis-ci.org/atom/notifications/builds/234162685?utm_source=github_status&utm_medium=notification)?

Comment (ungb) [inline lib/notification-issue.coffee]: Thanks, this should be fixed now! also added some test.

File: spec/notifications-spec.coffee [hunk 2]
```diff
@@ -263,6 +263,28 @@ describe "Notifications", ->
...
+
+          atom.notifications.addFatalError(stack, {detail, stack})
+          notificationContainer = workspaceElement.querySelector('atom-notifications')
+          fatalError = notificationContainer.querySelector('atom-notification.fatal')
+        it "title doesn't contain newline", ->
+          waitsForPromise ->
+            fatalError.getRenderPromise().then ->
+              issueTitle = fatalError.issue.getIssueTitle()
+          runs ->
+            expect(issueTitle).not.toContain "\n"
```
Comment (jasonrudolph) [inline spec/notifications-spec.coffee]: @ungb: Thanks for adding this test. :zap:

Based on this test, I see that we don't want the issue title to contain a newline. That tells us a bit about what the issue title should _not_ look like. Can I talk you into saying what the issue title _should_ look like? I think that will provide additional clarity regarding the expected behavior. 

Right now, as far as I can tell, the issue title has two spaces between "function" and "at":

    TypeError: undefined is not a function  at Object.module.exports.Pane.promptToSaveItem [as defau...

Does that matches your expectations?

Comment (ungb) [inline spec/notifications-spec.coffee]: I did some investigation and it seems like it does.  I tested this by forcing this to generate a url with the newlines not being removed and I get the following url to create a new issue:
```
https://github.com/atom/atom/issues/new?title=TypeError:+undefined+is+not+a+function%0A++at+Object.module.exports.Pane.promptToSaveItem+%5Bas+defau...&body=%5BEnter+steps+to+reproduce:%5D%0A%0A1.+...%0A2.+...%0A%0A**Atom**:+1.19.0-dev-85e65ffd1+x64%0A**Electron**:+1.6.9%0A**OS**:+Mac+OS+X+10.12.4%0A**Thrown+From**:+Atom+Core%0A%0A%0A%23%23%23+Stack+Trace%0A%0ATypeError:+undefined+is+not+a+function%0A++at+Object.module.exports.Pane.promptToSaveItem+%5Bas+defaultSavePrompt%5D+(/Applications/Atom.app/Contents/Resources/app/src/pane.js:490:23)%0A++at+PansdfsdfsdfsdPansdfsdfsdfsdfsdfsdffsdfsdfPansdfsdfsdfsdfsdfsdffsdfsdfPansdfsdfsdfsdfsdfsdffsdfsdffsdfsdffsdfsdf%0A%0A%0A%60%60%60%0AAt+undefined%0A%0ATypeError:+undefined+is+not+a+function%0A++at+Object.module.exports.Pane.promptToSaveItem+%5Bas+defaultSavePrompt%5D+(/Applications/Atom.app/Contents/Resources/app/src/pane.js:490:23)%0A++at+PansdfsdfsdfsdPansdfsdfsdfsdfsdfsdffsdfsdfPansdfsdfsdfsdfsdfsdffsdfsdfPansdfsdfsdfsdfsdfsdffsdfsdffsdfsdffsdfsdf%0A%0A%60%60%60%0A%0A%23%23%23+Commands%0A%0A%60%60%60%0A+++++-2:32.7.0+command-palette:toggle+(input.hidden-input)%0A+++++-2:31.8.0+editor:consolidate-selections+(input.hidden-input)%0A+++++-2:31.8.0+core:cancel+(input.hidden-input)%0A+++++-1:39.9.0+application:new-file+(ul.list-inline.tab-bar.inset-panel)%0A+++++-1:39+core:paste+(input.hidden-input)%0A+++++-1:28.6.0+core:copy+(input.hidden-input)%0A+++++-1:23.7.0+core:backspace+(input.hidden-input)%0A+++++-1:22.2.0+core:move-right+(input.hidden-input)%0A+++++-1:21.6.0+core:move-down+(input.hidden-input)%0A+++++-1:19.1.0+core:backspace+(input.hidden-input)%0A+++++-1:15.9.0+core:move-left+(input.hidden-input)%0A+++++-1:10.5.0+core:copy+(input.hidden-input)%0A%60%60%60%0A%0A%23%23%23+Non-Core+Packages%0A%0A%60%60%60%0Aatom-clock+0.1.7+%0Aatom-material-syntax+1.0.6+%0Aatom-material-ui+2.0.3+%0Amaterial-syntax+0.6.1+%0A%60%60%60%0A%0A
```

if you click on the link the title is:

```
TypeError: undefined is not a function  at Object.module.exports.Pane.promptToSaveItem [as defau...
```
Which has two spaces between function and at like you mention.  I'll add validate also to ensure we're getting the correct result from this.

Thanks,

Bryant
