### PR TITLE
Replace user profile in issue titles

### LINKED ISSUE #120: Replace user profile
Notifications should replace the user profile with something generic to reduce the number of duplicates (a great example of this is atom/atom#9559 - just keep scrolling down) ~~as well as to protect user privacy~~*.  @dirk-thomas referenced 30 duplicates...we're at 133 and counting, and atom/atom#10774 is at 36 right now :grimacing:.

For example, `/Users/username/Atom.app/whatever` could be replaced with `~/Atom.app/whatever`, and `C:\Users\username\stuff` could become `%USERPROFILE%\stuff`.

This has the potential to remove some important information such as non-ASCII characters in the username, but such cases are generally rare.  If needed we could add an extra `Username: ` line when a username is detected and the user opts in to it.

Refs #113.

\* Not currently feasible yet due to how Windows stack traces are formatted, so only the title gets replaced.  Perhaps later.

### PR DESCRIPTION
**Pull request by 50Wliu**
Fixes #120

### CODE REVIEW

File: lib/notification-issue.coffee [hunk 1]
```diff
@@ -55,7 +55,13 @@ class NotificationIssue
 
   getIssueTitle: ->
     title = @notification.getMessage()
-    title = title.replace(process.env.ATOM_HOME, '$ATOM_HOME')
+    if process.platform is 'win32'
+      title = title.replace(process.env.ATOM_HOME, '%ATOM_HOME%')
```
Comment (lee-dohm) [inline lib/notification-issue.coffee]: The text that will show up in the issue title should still be `$ATOM_HOME` so that cross-platform issues still match.

File: lib/notification-issue.coffee [hunk 2]
```diff
@@ -55,7 +55,13 @@ class NotificationIssue
...
+      title = title.replace(process.env.USERPROFILE, '%USERPROFILE%')
```
Comment (lee-dohm) [inline lib/notification-issue.coffee]: If this is the equivalent of `process.env.HOME` it should be replaced with `~`.

**Comment by 50Wliu** [comment]
@lee-dohm Comments have been addressed.  Windows issue titles should now appear exactly the same as those on OS X or Linux.

**Comment by lee-dohm** [comment]
Awesome, thanks!
